server:
  port: 8010

spring:
  data:
    mongodb:
      host: localhost
      port: 27018 # when flapdoodle using
      database: softi_ecommerce_products
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      
#de:
#  flapdoodle:
#    mongodb:
#      embedded:
#        version: 4.0.2

mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - com.softi.productservice.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    org:
      springframework:
        security: DEBUG
        wed: DEBUG